default:
  image: rust

test-all:
  stage: test
  script:
    - cargo test --all

check-all-no-default-features:
  stage: test
  script:
    - cargo check --all --no-default-features

check-alloc:
  stage: test
  script:
    - cargo check --no-default-features --features=alloc
