[workspace]
members = ["tests"]

[workspace.package]
version = "0.1.0-alpha.3"
edition = "2021"
rust-version = "1.64"

authors = ["Alexey Gerasev <alexey.gerasev@gmail.com>"]
repository = "https://github.com/agerasev/flatty.git"
license = "MIT/Apache-2.0"

[workspace.dependencies]
macros = { package = "flatty-macros", path = "macros", version = "0.1.0-alpha.3" }
base = { package = "flatty-base", path = "base", version = "0.1.0-alpha.3", default-features = false }
portable = { package = "flatty-portable", path = "portable", version = "0.1.0-alpha.3", default-features = false }

[package]
name = "flatty"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

authors.workspace = true
repository.workspace = true
license.workspace = true
readme = "README.md"
documentation = "https://docs.rs/flatty"
homepage = "https://github.com/agerasev/flatty"

[features]
default = ["std"]
std = ["base/std"]

[dependencies]
macros = { workspace = true }
base = { workspace = true }
portable = { workspace = true }
