[workspace]
members = ["base", "portable", "macros", "flatty", "tests"]

[workspace.package]

version = "0.1.0-alpha.2"
edition = "2021"
rust-version = "1.64"

authors = ["Alexey Gerasev <alexey.gerasev@gmail.com>"]
repository = "https://github.com/agerasev/flatty.git"
license = "MIT/Apache-2.0"
