[package]
name = "flatty-io"
version = "0.1.0-rc.0"
edition.workspace = true

description = "Flat message transfer"
authors.workspace = true
repository.workspace = true
license.workspace = true

[features]
default = ["async"]
async = ["futures"]

[dependencies]
flatty = { workspace = true, features = ["std"] }
futures = { version = "0.3.25", optional = true }

[dependencies.derive_more]
version = "0.99.17"
default-features = false
features = ["from", "into", "deref", "deref_mut"]

[dev-dependencies]
pipe = "0.4.0"
async-ringbuf = "0.1.0"
