[package]
name = "flatty"
version = "0.1.0-alpha.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base_ = { package = "flatty-base", path = "../flatty-base", version = "0.1.0-alpha.0" }
macros = { package = "flatty-macros", path = "../flatty-macros", version = "0.1.0-alpha.0" }
