[package]
name = "flatty-portable"
version.workspace = true
edition.workspace = true

description = "Flatty portable trait and primitives"
authors.workspace = true
repository.workspace = true
license.workspace = true

[features]
default = ["std"]
std = ["base/std", "num-traits/std"]

[dependencies]
base.workspace = true
num-traits = { version = "0.2", default-features = false }
