[package]
name = "flatty-base"
version.workspace = true
edition.workspace = true

description = "Flatty traits and primitives"
authors.workspace = true
repository.workspace = true
license.workspace = true
